name: parcial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  dropdown_button2: 2.0.0
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_rating_bar: 4.0.1
  flutter_svg: 2.0.4
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 4.0.3
  intl: 0.17.0
  json_path: 0.4.1
  page_transition: 2.0.4
  provider: 6.0.4
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  smooth_page_indicator: 1.0.1
  sqflite: 2.2.6
  table_calendar: 3.0.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
